//	disabledraw;

//強調レベル取得
	menu "em","strong";
	#ret = result;
	
	if( #ret == 0 ) endmacro;

//選択状態の判断～タグ挿入

	//選択状態の場合、選択範囲の前後にタグ挿入
	if( selecting == 1 ){
		//選択範囲を切り取り、配列変数に格納
		cut;
		beginclipboardread;
		#i = 0;
		$a[#i] = getclipboard;
		while( $a[#i] != "" ){
			#i = #i + 1;
			$a[#i] = getclipboard;
		}
		
		//配列変数に格納した文字列を結合して $OUT に格納
		$OUT = "";
		#j = 0;
		while( #i > #j ){
			$OUT = $OUT + $a[#j];
			#j = #j + 1;
		}
		
		//タグ挿入
		if( #ret == 1 ){
			$OUT = "<em>" + leftstr($OUT, strlen($OUT)) + "</em>";
		}
		else {
			$OUT = "<strong>" + leftstr($OUT, strlen($OUT)) + "</strong>";
		}
		insert $OUT;
		
		//クリップボード履歴をひとつ戻す
		getcliphist 1;
	}
	//非選択状態の場合、カーソル位置にタグ挿入
	else {
		if( #ret == 1 ){
			$OUT = "<em></em>";
		}
		else {
			$OUT = "<strong></strong>";
		}
		left 6;
	}

//	enabledraw;
	endmacro;
